### ISSUE TITLE
Import issues from the original `darglint` repository

### ISSUE THREAD

**Issue by akaihola** [akaihola/darglint2#10]
In [this comment](/akaihola/darglint2/pull/1#issuecomment-1436406700), @real-yfprojects pointed out that there's [a script](https://gist.github.com/agarny/5541773) which could be used to carry over issues from the original repository to this one.

The issues would appear under the name of whoever uses the script.

I'm not sure we want to bulk migrate each and every issue. Let's discuss.

**Comment by real-yfprojects** [comment]
> I'm not sure we want to bulk migrate each and every issue. Let's discuss.

You are right. I would migrate the issues I would want to see tackled. That is (valid) bugs and notable feature requests.
