### ISSUE TITLE
Explain reason for forking `darglint` in the `README`

### ISSUE THREAD

**Issue by akaihola** [akaihola/darglint2#11]
>I propose adding a sentence why it was forked.

_Originally posted by @real-yfprojects in https://github.com/akaihola/darglint2/pull/1#discussion_r1121198399_

**Comment by real-yfprojects** [comment]
I would include that in the initial release (1.8.2).

**Comment by akaihola** [comment]
I agree, I'll do that.

**Comment by akaihola** [comment]
Decided to finally just get 1.8.2 out and include this in 1.8.3. When this `README` addition lands in `main`, it will anyway appear on the GitHub front page of the repository, and PyPI will show it after 1.8.3 is published.
