### ISSUE TITLE
Decide the build system to use

### ISSUE THREAD

**Issue by akaihola** [akaihola/darglint2#13]
_Originally posted by @real-yfprojects in [a comment to issue #1](https://github.com/akaihola/darglint2/issues/1#issuecomment-1437534712_):
            
~~Do you plan on packaging with setuptools? I would prefer keeping poetry.~~ I am already tired and I don't get the current packaging config with both `setup.py` and `pyproject.toml`.

**Comment by akaihola** [comment]
@real-yfprojects, I'm also confused about why [terrencepreilly/darglint](https://github.com/terrencepreilly/darglint/) had both. I'm very familiar with [setuptools](https://setuptools.pypa.io/), I've never really understood [poetry](https://python-poetry.org/), and I'm liking [flit](https://flit.pypa.io/) a lot whenever more advanced features are not needed.

For the 1.8.x series I'm not planning to change the build system. For 1.9.0 we could consider if there's a good reason. Thanks for bringing up the topic, let's have the discussion here.

**Comment by real-yfprojects** [comment]
> I'm very familiar with [setuptools](https://setuptools.pypa.io/), I've never really understood [poetry](https://python-poetry.org/),

I use both in my projects already. No experience with flit. But I this could be an opportunity to change that. 

> I'm not planning to change the build system.

So we are using *poetry* then? It is configured in `pyproject.toml` overriding any *setuptools* configuration.

**Comment by akaihola** [comment]
>we are using _poetry_?

I believe that's the case. There are also `poetry.lock` files for the `darglint2` package as well as the `bin/bnf_to_cnf` and `bin/doc_extract` tools.

**Comment by real-yfprojects** [comment]
> For 1.9.0 we could consider if there's a good reason. Thanks for bringing up the topic, let's have the discussion here.

I like poetry although it has some downsides like the impossibility of including dev tools in the python environment locally without including them in `pyproject.toml` which at the same time is one of the main reasons to use it.

**Comment by akaihola** [comment]
I'm ok with staying with poetry.

**Comment by real-yfprojects** [comment]
We can close this then I suppose.
