### ISSUE TITLE
Omit original author's e-mail address

### ISSUE THREAD

**Issue by akaihola** [akaihola/darglint2#17]
>I'm not too particular about that.  You could just leave it in a comment, or the readme.  Or just remove it and link to the original repo on github.  It's probably best to not include my email, because I'll only check it once a week or so, and I don't want to give a false impression that I'd be very responsive.

_Originally posted by @terrencepreilly in https://github.com/akaihola/darglint2/pull/1#discussion_r1102257975_

**Comment by real-yfprojects** [comment]
We already link Terrence and his repo. I will remove his email addr in #15.
