### ISSUE TITLE
Use separate configurations in isolated tests

### ISSUE THREAD

**Issue by akaihola** [akaihola/darglint2#20]
>I ran into a not so small problem. I configured darglint2 so we can use it for qa in this repository. However the tests load their config from the configuration file too and fail since they rely on the default configuration. IMO tests should run in a stable, strictly defined environment. The config should also be dynamically editable to test different configurations. According to source comments this is currently not possible. For now I implemented a fixture that overrides the config with its default values.

_Originally posted by @real-yfprojects in https://github.com/akaihola/darglint2/issues/16#issuecomment-1465132143_

**Comment by real-yfprojects** [comment]
Instead of managing a global config instance, passing the config object as a parameter might be better - similar to how one would do it javascript. What do you think?

**Comment by akaihola** [comment]
Could you open a pull request which adds the darglint2 configuration for qa in the repository itself? It will be easier to discuss this once I can see the test failures, too. Thanks!

**Comment by real-yfprojects** [comment]
> Could you open a pull request which adds the darglint2 configuration for qa in the repository itself?

I don't get exactly what you mean.

**Comment by akaihola** [comment]
Ok, maybe I've misunderstood. You said:
>I configured darglint2 so we can use it for qa in this repository.

I understood this as you've tried to add a `.darglint2` configuration file to this repository.

>tests load their config from the configuration file too and fail since they rely on the default configuration

This one I interpreted as when running `pytest`, the configuration that the tests use would now read the new `.darglint2`, giving different results than originally when there was no configuration file and thus the default configuration was being used for tests.

Did I misunderstand this?

If not, I meant to suggest that you'd create a branch with your added `.darglint2` file, submit it as a Pull Request, and I would then be able to reproduce that situation on my laptop. This would help in getting on the same page with you and understanding what our options are for solving the issue.

**Comment by real-yfprojects** [comment]
> Did I misunderstand this?

Partly. The darglint2 configuration was merged with mentioned PR since it was included in `tox.ini`. However that made the tests fail. So I worked around that by overriding the loaded configuration in a pytest fixture. 

I wouldn't consider the current configuration implementation to be clean but it does the job so we don't actually need a change at the moment.

**Comment by akaihola** [comment]
Ok, I see. So the `tox.ini` modification was in [`3dae74e`](https://github.com/akaihola/darglint2/commit/3dae784ec2985fdf9165490358ad043add6eaa09#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449) ("Configure pre-commit hooks.", 2023-03-09), and the Pytest configuration in 513db0307bb694fef632dbecf9d39d9dbbe1386d ("Enforce default config in tests.", 2023-03-12).

I think this is a decent work-around. If anything, there could be an explanation in `tests/conftest.py:default_config`.

**Comment by real-yfprojects** [comment]
> I think this is a decent work-around. If anything, there could be an explanation in `tests/conftest.py:default_config`.

Right will add that. I will leave the work-around in place. However I am currently looking into simplifying the configuration code. At the moment arguments have to be 'defined' in multiple places for parsing from different configuration files and such. I saw people extending `argparse` to define config options in one place while parsing config files too.

**Comment by real-yfprojects** [comment]
> At the moment arguments have to be 'defined' in multiple places for parsing from different configuration files and such.

My research was pretty disappointing so far. I couldn't find any library (or existing code) providing a framework for reading multiple configuration files and formats like we do.

**Comment by akaihola** [comment]
So continue research, postpone it until later, or leave the code as is?

**Comment by real-yfprojects** [comment]
> So continue research, postpone it until later, or leave the code as is?

I'll postpone this and open a new issue based on my new insights into the configuration setup. Though I will open a PR with the cleanup I have already done.
