### ISSUE TITLE
Allow configuration in `pyproject.toml`

### ISSUE THREAD

**Issue by liebsc21** [akaihola/darglint2#42]
Is it possible to allow configuration in `pyproject.toml` instead of `.darglint2`, `.darglint`, `setup.cfg`, or `tox.ini`?

**Comment by akaihola** [comment]
Hi @liebsc21, thanks a lot for your question!

In the current version, `pyproject.toml` is not supported.

Also, as stated in the README,
>`darglint2` is only intended as a low-effort replacement for `darglint` for those old darglint users who need bugfixes and critical features but don't want to spend the trouble of migrating to a better alternative. See e.g. [this discussion](https://github.com/jsh9/pydoclint/discussions/9) for details.

I will still review and accept a good pull request for this feature if you can spend the effort to implement it (or find someone else to do that).

As for myself, I try to stick to the principle above, and stay just as a maintainer. I won't implement new features myself unless the lack of a feature makes it difficult to use `darglint2` or prevents it from working altogether.

**Comment by liebsc21** [comment]
Thanks, I was not aware of pydoclint. I think I will use it instead.
